import { saveInvoiceToDB } from "../../supabase.js";
import { effectivePrice, getWalkerPayout, getBookingWeekKey } from "../../helpers.js";

// ─── Invoice Helpers ──────────────────────────────────────────────────────────
function generateInvoiceId() {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, "0");
  const d = String(now.getDate()).padStart(2, "0");
  const rand = Math.floor(Math.random() * 9000) + 1000;
  return `INV-${y}${m}${d}-${rand}`;
}

function getInvoiceDueDate(sentAt) {
  const d = new Date(sentAt || new Date());
  d.setDate(d.getDate() + 7);
  return d.toISOString();
}

// Auto-generate a single-walk invoice the moment a walk is marked complete.
// Returns an updated clientRecord with the invoice appended, or the original
// if an invoice for this booking already exists (prevents duplicates).
function autoCreateWalkInvoice(clientRecord, booking) {
  // Never auto-invoice historical entries — they're records, not new charges
  if (booking.isHistoricalEntry) return clientRecord;

  const alreadyInvoiced = (clientRecord.invoices || []).some(inv =>
    (inv.items || []).some(it => it.bookingKey === booking.key)
  );
  if (alreadyInvoiced) return clientRecord;

  const now = new Date().toISOString();
  const amount = effectivePrice(booking);
  const newInvoice = {
    id: generateInvoiceId(),
    type: "walk",
    items: [{
      bookingKey: booking.key,
      description: `${booking.form?.pet || "Pet"} · ${booking.slot?.duration || ""} · ${booking.day || ""}, ${booking.date || ""}`,
      amount,
    }],
    subtotal: amount,
    total: amount,
    notes: "",
    status: "sent",
    createdAt: now,
    sentAt: now,
    dueDate: getInvoiceDueDate(now),
    autoGenerated: true,
  };

  return {
    ...clientRecord,
    invoices: [...(clientRecord.invoices || []), newInvoice],
  };
}

function invoiceStatusMeta(status, dueDate) {
  const isOverdue = status === "sent" && dueDate && new Date(dueDate) < new Date();
  const effectiveStatus = isOverdue ? "overdue" : status;
  const map = {
    draft:   { label: "Draft",   color: "#6b7280", bg: "#f3f4f6", border: "#e4e7ec" },
    sent:    { label: "Pending", color: "#b45309", bg: "#fffbeb", border: "#fde68a" },
    overdue: { label: "Overdue", color: "#dc2626", bg: "#fef2f2", border: "#fecaca" },
    paid:    { label: "Paid",    color: "#059669", bg: "#FDF5EC", border: "#F0E8D5" },
  };
  return { ...map[effectiveStatus] || map.draft, effectiveStatus };
}

function getAllInvoices(clients) {
  const all = [];
  Object.values(clients).forEach(c => {
    (c.invoices || []).forEach(inv => all.push({ ...inv, clientName: c.name, clientEmail: c.email }));
  });
  return all.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
}


export { generateInvoiceId, getInvoiceDueDate, autoCreateWalkInvoice, invoiceStatusMeta, getAllInvoices };
